# Hydrangea Bright Night
[colors]
foreground = "#818592"
background = "#2c303a"
cursor_bg = "#a60062"
cursor_border = "#a60062"
cursor_fg = "#2c303a"
selection_bg = "#3d788f"
selection_fg = "#7fb8d0"

ansi = [
    "#474b56",
    "#8e004f",
    "#486533",
    "#6d763c",
    "#475c8f",
    "#6e4aa7",
    "#27647a",
    "#969aa7",
]
brights = [
    "#818592",
    "#d62d8a",
    "#84a36c",
    "#c2cb8c",
    "#8699d1",
    "#b086eb",
    "#69a2ba",
    "#d8dcea",
]

