# Spacegray Dark
[colors]
foreground = "#c0c5ce"
background = "#2b303b"
cursor_bg = "#c0c5ce"
cursor_border = "#c0c5ce"
cursor_fg = "#2b303b"
selection_bg = "#c0c5ce"
selection_fg = "#2b303b"

ansi = [
    "#2b303b",
    "#bf616a",
    "#a3be8c",
    "#ebcb8b",
    "#8fa1b3",
    "#b48ead",
    "#96b5b4",
    "#a7adba",
]
brights = [
    "#65737e",
    "#bf616a",
    "#a3be8c",
    "#ebcb8b",
    "#8fa1b3",
    "#b48ead",
    "#96b5b4",
    "#c0c5ce",
]
